### ISSUE TITLE
dialparties.agi permission denied

### ISSUE THREAD

**Issue by maptan** [IssabelFoundation/framework#16]
got an issue, where a timecondition pointed to an extension or virtual extension, where follow me redirected to an external number. this did not work, and on log I could see permission denied for dialparties.agi.
fixed it using an old thread on elastix fforum ( https://www.elastix.org/community/threads/dialparties-permission-problem.129534/).

You may edit:
/var/lib/asterisk/bin/retrieve_conf
/var/www/html/admin/modules/framework/bin/retrieve_conf

and under the cp_subdirs function change 0754 to 0755

then execute:
/var/lib/asterisk/bin/retrieve_conf
asterisk -rx "module reload"

**Comment by asternic** [comment]
Thanks, fixed.
