### ISSUE TITLE
API sets wrong month on time groups

### ISSUE THREAD

**Issue by seederp2p** [IssabelFoundation/framework#28]
You should correct the framework/html/pbxapi/controllers/timegroups.php because as it is won’t properly configure months (it only allows numeric months but that will result in the asterisk ignoring the month).

Suggestion:

$validmonths = array('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec');

            } else if ($key=='start_month') {
                if(!in_array($finalval[$key],$validmonths)) {
                    $errors[]=array('status'=>'422','source'=>'start_month','detail'=>'Incorrect format. Allowed values: jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec or *');
                }
            } else if ($key=='end_month') {
                if(!in_array($finalval[$key],$validmonths)) {
                    $errors[]=array('status'=>'422','source'=>'end_month','detail'=>'Incorrect format. Allowed values: jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec');
                }

**Comment by asternic** [comment]
thanks, fixed
