### ISSUE TITLE
Additional themes

### ISSUE THREAD

**Issue by powerpbx** [IssabelFoundation/framework#6]
`yum install issabel-framework-themes-extra` doesn't install extra themes.

I was able to do it by using `rpm -Uvh http://repo.elastix.org/elastix/4/extras/x86_64/RPMS/elastix-framework-themes-extra-4.0.0-18.noarch.rpm`

That installs extra themes in `/var/www/html/themes` which can then be selected in the GUI.  I can't find these themes here so perhaps we can create a repository for them?

**Comment by asternic** [comment]
We removed all extra themes for now, so the package is actually empty. We want to concentrate on stability and security for now, and we will probably initiate a transition to a new GUI, so working on different themes although possible by now, it is not a priority.. some themes might break functionality and we do not have the resources/time to look into them.
